Accueil
WildCodeSchool-2024-02/js-valence-p3-eating-nam-nam pull request #16
Opened 2024-06-21 13:13 UTC by derimer

page d accueil desktop et responsive

2024-06-21 13:43 UTC, Hasbem requested changes
Tu as laissé des id vide dans tes inputs
fais les import dans le fichier import.js
utilise les variables css
enlève l'import de font dans ton accueil.css, ils sont deja dans app.css
fais l'export de App à la fin de ton fichier
il y à déjà une branche pour le router
tu ne devrais pas mettre tes témoignages en li
change la taille de tes boutons

2024-06-21 13:43 UTC, Hasbem commented on client/src/components/Accueil.jsx
> +          <input type="text" name="" id="" placeholder="S'inscrire" />
ID vide

2024-06-21 13:43 UTC, Hasbem commented on client/src/components/Accueil.jsx
> +import table from "../assets/images/DSC_4636-1024x682 (1).jpg";
Fais tes imports dans ./components/import.js

2024-06-21 13:59 UTC, Hasbem requested changes

2024-06-21 13:59 UTC, Hasbem commented on client/src/components/Accueil.css
utilise les variables css, ça sera plus simple pour les couleurs et les fonts

2024-06-21 13:59 UTC, Hasbem commented on client/src/components/Accueil.css
> +@import url("https://fonts.googleapis.com/css2?family=Aleo:ital,wght@0,100..900;1,100..900&display=swap"); /* Réinitialiser le padding pour tous les éléments */
enlève l'import de font, il est déjà dans app.css

2024-06-21 13:59 UTC, Hasbem commented on client/src/App.jsx
> +export default function App() {
fais l'export de App à la fin de ton fichier

2024-06-21 13:59 UTC, Hasbem commented on client/src/components/Accueil.jsx
> +export default function Accueil() {
fais l'export d'Accueil à la fin de ton fichier

2024-06-21 13:59 UTC, Hasbem commented on client/src/App.jsx
> +/* import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
Il y à une branche pour le router, et cela se fait dans le main.jsx

2024-06-21 13:59 UTC, Hasbem commented on client/src/components/Accueil.jsx
> +          <ul className="temoins">
Les témoignages ne devraient pas être en li

2024-06-21 13:59 UTC, Hasbem commented on client/src/App.css
change la taille de tes boutons

2024-06-27 08:11 UTC, BENSFIA commented
valider

2024-06-27 08:26 UTC, Angeline3107 commented
ok pou review

2024-06-27 08:37 UTC, nimser reviewed
Can't seem to find where the Accueil page gets included?

2024-06-27 08:51 UTC, nimser requested changes

2024-06-27 08:51 UTC, nimser commented on client/src/pages/Accueil.jsx
> +import table from "../assets/images/table.jpg";
Fais tes imports dans ./components/import.js

2024-06-27 09:02 UTC, nimser requested changes

2024-06-27 09:02 UTC, nimser commented on client/src/pages/Accueil.jsx
> +          <div className="temoins">
Remove `<div>`, put class in `<ul>`

2024-07-02 12:23 UTC, Angeline3107 approved these changes

2024-07-02 12:31 UTC, Angeline3107 approved these changes

2024-07-02 12:39 UTC, Angeline3107 approved these changes

2024-07-02 12:40 UTC, Angeline3107 approved these changes

2024-07-02 12:43 UTC, Angeline3107 approved these changes

2024-07-02 12:45 UTC, Angeline3107 approved these changes
ok j'approuve

2024-07-02 12:53 UTC, Angeline3107 approved these changes

2024-07-02 12:54 UTC, Hasbem approved these changes

2024-07-02 13:31 UTC, nimser approved these changes

2024-07-02 13:31 UTC, merged