Navbar
WildCodeSchool-2024-02/js-valence-p3-eating-nam-nam pull request #36
Opened 2024-06-26 07:26 UTC by Hasbem

2024-06-26 07:32 UTC, derimer approved these changes
ok

2024-06-26 09:21 UTC, nimser requested changes
Some refactoring to do. Please see comments.

2024-06-26 09:21 UTC, nimser commented on client/src/components/Navbar.jsx
Way too much imbrication. Also avoid the use of `div` and classes.

2024-06-26 09:21 UTC, nimser commented on client/src/styles/Navbar.css
Favour selectors of high specificity using element names (e.g `header  > nav`) instead of classes.

2024-06-26 09:21 UTC, nimser commented on client/src/styles/Navbar.css
> +  z-index: 1;
Please justify why you need a z-index here.

2024-06-26 09:21 UTC, nimser commented on client/src/styles/Navbar.css
> +  position: absolute;
avoid position: absolute when there are other options (e.g. flexbox)

2024-06-27 06:59 UTC, BENSFIA commented
elle est prête

2024-06-27 09:29 UTC, nimser requested changes
The Navbar component should be included in the main layout.

2024-06-27 09:31 UTC, nimser approved these changes

2024-06-27 09:53 UTC, merged