creation dan admin  des pages Gestion recettes Gestion utilisateur
WildCodeSchool-2024-02/js-valence-p3-eating-nam-nam pull request #90
Opened 2024-07-24 12:28 UTC by BENSFIA

merci de vérifier mon code

2024-07-24 12:57 UTC, Angeline3107 requested changes

2024-07-24 12:57 UTC, Angeline3107 commented on client/src/assets/icones/troispoints.png:Zone.Identifier
Il faut ajouter `*:Zone.Identifier` dans .gitignore pour eviter que ce genre de fichiers soient commités

2024-07-25 08:17 UTC, Angeline3107 reviewed
[FAILED] eslint --report-unused-disable-directives [FAILED]
[FAILED] eslint --report-unused-disable-directives [FAILED]

2024-07-25 09:13 UTC, nimser requested changes

2024-07-25 09:13 UTC, nimser commented on client/src/api/fetch.js
> +export async function fetchRecetteById(id) {
Pas besoin de celui ci

2024-07-25 09:13 UTC, nimser commented on client/src/pages/admin/GestionRecettes.jsx
> +  const handleDelete = async (recette) => {
Créer une fonction `fetchDeleteRecetteById` (dans api/fetch.js)

2024-07-25 09:13 UTC, nimser commented on client/src/pages/admin/GestionRecettes.jsx
> +      const response = await fetch(`recettes/${recette.id}`, {
Ce fetch ne fait rien car :
- aucun `body` n'est passé
- aucune route n'est crée coté server (router.js)

2024-07-25 09:13 UTC, nimser commented on client/src/pages/admin/GestionRecettes.jsx
> +        method: "PUT",
Utiliser une méthode PATCH car il s'agit de la modification d'un seul attribut de la recette. 
Faire de même coté server (`router.patch()`)

2024-07-25 09:13 UTC, nimser commented on client/src/pages/admin/GestionUtilisateur.jsx
> +  const handleDelete = async (user) => {
Vider cette fonction, et à la place appeler la fonction `fetchDeleteUserById` (dans api/fetch.js)

2024-07-25 09:13 UTC, nimser commented on client/src/styles/Admin.css
> +* {
Mettre dans le App.css si vraiment nécessaire

2024-07-25 09:13 UTC, nimser commented on client/src/styles/GestionIngredient.css
> +* {
Code inutile (déjà présent dans Admin.css et doit être déplacé dans App.css)

2024-07-25 09:13 UTC, nimser commented on client/src/styles/GestionIngredient.css
> +.ul1,
Pas de nom de classe avec des nom d'éléments

2024-07-25 09:13 UTC, nimser commented on client/src/styles/GestionUtilisateur.css
> +* {
idem

2024-07-25 09:13 UTC, nimser commented on client/src/styles/GestionUtilisateur.css
Ajouter une classe parente pour la page

2024-07-25 09:13 UTC, nimser commented on client/src/styles/GestionUtilisateur.css
> +  li1 {
idem

2024-08-01 08:57 UTC, Angeline3107 approved these changes

2024-08-01 09:00 UTC, closed without merging